export {
  StyledIconContainer,
  ServicesMainContainer,
  ServicesMainTitle,
  WaterSplash,
  RightSideWaterSplash,
  BottomWaterSplash,
  ReverseInternalContentContainer,
  ContentBox,
  ContactLink,
  InternalContentContainer,
  ContentBoxTitle,
  ContentBoxText,
  ExternalContentContainer,
  UniqueExternalContentContainer,
} from "./StyledServicesContent";
export {
  ContactContainer,
  SimpledLayer,
  BackgroundLayer,
  StyledRelIconContainer,
  MainTitle,
  FormContainer,
  ContactInfoContainer,
  ContactInfo,
  StyledLogoImage,
} from "./StyledContactContent";
